# Generated by Django 4.2.1 on 2023-05-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(max_length=100)),
                ("conservation_status", models.CharField(max_length=100)),
            ],
        ),
    ]
