# Generated by Django 4.2.1 on 2023-06-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "food_type",
                    models.CharField(
                        choices=[("W", "Worm"), ("B", "Berry"), ("S", "Seed")],
                        default="W",
                        max_length=1,
                    ),
                ),
                (
                    "finch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.finch"
                    ),
                ),
            ],
        ),
    ]
