# Generated by Django 4.2.1 on 2023-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="feeding",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="feeding",
            name="date",
            field=models.DateField(verbose_name="Feeding date"),
        ),
    ]
