# Generated by Django 4.2.1 on 2023-06-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_location_alter_feeding_options_alter_feeding_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="finch",
            name="locations",
            field=models.ManyToManyField(to="main_app.location"),
        ),
    ]
